ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageFinderUserStudyWeb.Pages
{
    public class AboutModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your application description page.";
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Contact.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageFinderUserStudyWeb.Pages
{
    public class ContactModel : PageModel
    {
        public string Message { get; set; }

        public void OnGet()
        {
            Message = "Your contact page.";
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageFinderUserStudyWeb.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/ImageGallery.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageFinderUserStudyWeb.Pages
{
    public class ImageGalleryModel : PageModel
    {
        private readonly UserSessions UserSessionsHolder;

        private readonly GlobalConfig GlobalConfigHolder;

        public UserSessionInfo UserSession { get; private set; }

        public int NumberOfColumns { get; private set; }

        public int NumberOfRows { get; private set; }

        public int PictureWidthPixels { get; private set; }

        public int GalleryWidthPixels { get; private set; }

        public int GalleryHeightPixels { get; private set; }

        public ImageGalleryModel(
            UserSessions userSessionsInfo,
            GlobalConfig globalConfig
            )
        {
            UserSessionsHolder = userSessionsInfo;
            GlobalConfigHolder = globalConfig;
        }

        public string SizeInPixels(int size)
        {
            return $"{size}px";
        }

        public string ImagePath(string imageId)
        {
            return "http://herkules.ms.mff.cuni.cz/lineit/20k_images/images/" + $"{imageId}.jpg";
        }

        public void OnGetGallery(Guid userSessionGuid)
        {
            UserSession = UserSessionsHolder.GetUserSessions[userSessionGuid];

            NumberOfRows = UserSession.SortedResult.GetLength(0);
            NumberOfColumns = UserSession.SortedResult.GetLength(1);

            GalleryWidthPixels = GlobalConfigHolder.GalleryWidthPixels;
            GalleryHeightPixels = GlobalConfigHolder.GalleryHeightPixels;

            PictureWidthPixels = GalleryWidthPixels / NumberOfColumns;

            UserSession.UpdateGaleryDisplayTime(DateTime.Now);

            UserSession.NumberOfRowsPresented = NumberOfRows;
            UserSession.NumberOfColumnsPresented = NumberOfColumns;
            UserSession.GalleryPixelWidth = GalleryWidthPixels;
            UserSession.GalleryPixelHeight = GalleryHeightPixels;
        }

        public IActionResult OnPostImageClick(Guid userSessionGuid, string imageId)
        {
            UserSession = UserSessionsHolder.GetUserSessions[userSessionGuid];

            UserSession.FoundImageId = imageId;

            UserSession.TimeTakenToRespond = DateTime.Now - UserSession.TimeOfGalleryDisplay;

            UserSession.UserHasFoundImage(imageId);

            return RedirectToPage("SummaryPage", "Summary", new { userSessionId = userSessionGuid });
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/ImagePresentation.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using UserStudyImageFinderRanker;

namespace ImageFinderUserStudyWeb.Pages
{
    public class ImagePresentationModel : PageModel
    {
        public string ImageId { get; private set; }

        public Guid UserSessionId { get; private set; }

        public ImageLabels UserImageLabels;

        private readonly ImageLabelsWrapper ImageLabelsHolder;
        private readonly UserSessions UserSessionsHolder;
        private readonly GlobalConfig GlobalConfigHolder;

        public ImagePresentationModel(
            ImageLabelsWrapper imageLabelsWrapper,
            UserSessions userSessions,
            GlobalConfig globalConfig)
        {
            ImageLabelsHolder = imageLabelsWrapper;
            UserSessionsHolder = userSessions;
            GlobalConfigHolder = globalConfig;

            UserSessionId = Guid.NewGuid();

            var imageSelector = new RandomImageSelector();
            var selectedImagePosition = imageSelector.SelectImageId(ImageLabelsHolder.LoadedImageLabels);

            UserImageLabels = ImageLabelsHolder.LoadedImageLabels[(int)selectedImagePosition];
            ImageId = UserImageLabels.ImageId;
        }

        public string ImagePath(string imageId)
        {
            return "http://herkules.ms.mff.cuni.cz/lineit/20k_images/images/" + $"{imageId}.jpg";
        }

        public async Task OnGetAsync()
        {
            await Task.Run(() => UserSessionsHolder.AddNewUserSession(
                UserSessionId, UserImageLabels,
                GlobalConfigHolder.NumberOfImagesToPresent, GlobalConfigHolder.NumberOfColumnsInGallery));
        }

        public IActionResult OnPostGallery(Guid userSessionId)
        {
            return RedirectToPage("ImageGallery", "Gallery", new { userSessionGuid = userSessionId });
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageFinderUserStudyWeb.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ImageFinderUserStudyWeb.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/SummaryPage.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace ImageFinderUserStudyWeb.Pages
{
    public class SummaryPageModel : PageModel
    {
        private readonly UserSessions UserSessionsHolder;

        public UserSessionInfo UserSession { get; private set; }

        public SummaryPageModel(
            UserSessions userSessions)
        {
            UserSessionsHolder = userSessions;
        }

        public void OnGetSummaryAsync(Guid userSessionId)
        {
            UserSession = UserSessionsHolder.GetUserSessions[userSessionId];

            string filePath = "userSessions/" + UserSession.UserSessionId + ".json";

            System.IO.File.WriteAllText(filePath, JsonConvert.SerializeObject(UserSession));
        }
    }
}

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/About.cshtml
@page
@model AboutModel
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<p>A web created to find the best way how to sort a set of images so the one image the user is looking for is easily found.</p>

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Contact.cshtml
@page
@model ContactModel
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@Model.Message</h3>

<address>
    <strong>Support:</strong> <a href="mailto:simon.schagerer@gmail.com">simon.schagerer@gmail.com</a><br />
</address>

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/ImageGallery.cshtml
@page
@model ImageFinderUserStudyWeb.Pages.ImageGalleryModel
@{
    ViewData["Title"] = "ImageGallery";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container">
    <style>
        h2 {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        p {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        form {
            margin: auto;
            text-align: center;
        }
    </style>
    <h2>Image Gallery</h2>
    <p>Find the image or say it's not present!</p>
    <form method="post" asp-page-handler="ImageClick">
        <button class="btn btn-default">
            Image is not present.
        </button>
        <input type="hidden" name="userSessionGuid" value="@Model.UserSession.UserSessionId" />
        <input type="hidden" name="imageId" value="NotPresent" />
    </form>
    <div class="table-wrapper" id="imageGallery" style="overflow:auto;height:@Model.SizeInPixels(Model.GalleryHeightPixels);width:@Model.SizeInPixels(Model.GalleryWidthPixels);margin:auto;">
        <table align="center">
            @for (int row = 0; row < Model.NumberOfRows; row++)
            {
                <tr style="height:@Model.SizeInPixels(Model.PictureWidthPixels);width:@Model.SizeInPixels(Model.GalleryWidthPixels);">
                    @for (int column = 0; column < Model.NumberOfColumns; column++)
                    {
                        <td style="height:@Model.SizeInPixels(Model.PictureWidthPixels);width:@Model.SizeInPixels(Model.PictureWidthPixels);">
                            <form method="post" asp-page-handler="ImageClick" style="height:@Model.SizeInPixels(Model.PictureWidthPixels);width:@Model.SizeInPixels(Model.PictureWidthPixels);">
                                <button type="submit" style="height:@Model.SizeInPixels(Model.PictureWidthPixels);width:@Model.SizeInPixels(Model.PictureWidthPixels);background:none;border:none;padding:0">
                                    <img src=@Model.ImagePath(Model.UserSession.SortedResult[row, column]) style="height:@Model.SizeInPixels(Model.PictureWidthPixels);width:@Model.SizeInPixels(Model.PictureWidthPixels);">
                                </button>
                                <input type="hidden" name="userSessionGuid" value="@Model.UserSession.UserSessionId" />
                                <input type="hidden" name="imageId" value="@Model.UserSession.SortedResult[row, column]" />
                            </form>
                        </td>
                    }
                </tr>
            }
        </table>
    </div>
</div>

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/ImagePresentation.cshtml
@page
@model ImageFinderUserStudyWeb.Pages.ImagePresentationModel
@{
    ViewData["Title"] = "Image presentation";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="container">
    <style>
        h2 {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        p {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        form {
            margin: auto;
            text-align: center;
        }
    </style>
    <h2>Image Presentation</h2>
    <p>Remember this image.</p>
    <img src="@Model.ImagePath(Model.ImageId)" style="height:500px;width:700px;" class="center-block" />
    <form method="post" asp-page-handler="Gallery">
        <button class="btn btn-default">
            Continue to image gallery
        </button>
        <input type="hidden" name="userSessionId" value="@Model.UserSessionId" />
    </form>
</div>

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container" id="myCont">
    <style>
        h2 {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }
        p {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }
        form {
            margin: auto;
            text-align: center;
        }
    </style>
    <h2>Image finder</h2>
    <p>
        Welcome to image finder web app.
    </p>
    <p>
        Click the button to continue to a page which will provide an image.
    </p>
    <p>
        You will have to remember the image and then try finding it in a set of presented images.
    </p>
    <form method="get">
        <button type="submit" asp-page="./ImagePresentation" id="IndexPageContinueButton">
            Continue
        </button>
    </form>
    
</div>

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Image Finder</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-page="/Index" class="navbar-brand">Image Finder</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-page="/Index">Home</a></li>
                    <li><a asp-page="/About">About</a></li>
                    <li><a asp-page="/Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        <style>
            p {
                text-align: center;
                margin-left: auto;
                margin-right: auto;
            }
        </style>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Image Finder Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

ImageFinderUserStudyWeb/ImageFinderUserStudyWeb/Pages/SummaryPage.cshtml
@page
@model ImageFinderUserStudyWeb.Pages.SummaryPageModel
@{
    ViewData["Title"] = "SummaryPage";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}


<div class="container">
    <style>
        h2 {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        p {
            text-align: center;
            margin-left: auto;
            margin-right: auto;
        }

        form {
            margin: auto;
            text-align: center;
        }
    </style>
    <h2>Summary</h2>
    <p>
        @if (Model.UserSession.AnsweredCorrectly)
        {
            <text> You have answered correctly. </text>
        }
        else
        {
            <text> You have answered incorrectly. </text>
        }
    </p>
    <p>
        Number of seconds to respond: @Model.UserSession.TimeTakenToRespond.Seconds
    </p>
    <p>
        Thank you for your participation.
    </p>
    <form method="get" asp-page="Index">
        <button class="btn btn-default">
            Return home
        </button>
    </form>
</div>